#!/bin/bash

# This script will make sure that only single node process gets run

LOG_FILE="logs/`hostname`.log"
PID_FILE="logs/node.pid"

echo "Starting node with parameters: $@" > $LOG_FILE

if [ -f $PID_FILE ]; then
    
    # check to see if the old PID is still running
    pid=`cat $PID_FILE`
    `kill -0 $pid > /dev/null 2>&1`
    not_running=$?

    if [ $not_running -ne 0 ]; then
        echo "Removing orphanged pid file" >> $LOG_FILE
        rm $PID_FILE 
    else 
        echo "Node already running. Exiting" >> $LOG_FILE
        echo "Node already running on `hostname`"
        exit 1
    fi
fi

python python/experiment_Node.py $1 >> $LOG_FILE 2>&1 &
echo "$!" > $PID_FILE

