#!/bin/bash

# This is the file that will eventually control all of th testing
# This file will push all the code to the nodes and then run the tests. 
# New code must be supported by this script

NUM_ARGS=1
USAGE="Usage: start {xml-test-file} "
USERS="blue"

if [ $# -ne $NUM_ARGS ]; then
    echo $USAGE
    exit 1
fi

# lets explore the network and see what is connected
echo "finding nodes..."
nodes=`./scripts/get_hosts`
echo "Found nodes: $nodes"

# lets push the code to the nodes
echo "updating node's code"
for node in $nodes; do
    ./scripts/sync $node
done
echo "done updating code"

echo "Starting nodes..."
for node in $nodes; do
    id=`ssh "$USERS@$node" hostname | cut -c6-`
    echo "Starting node-$id"
    ssh "$USERS@$node" "python research/364d-udp/python/experiment_Node.py $id &" 
done
echo "nodes started"

echo "Starting experiment."
python python/experiment_AP.py
echo "Done."

