#!/bin/bash

# This is the file that will eventually control all of th testing
# This file will push all the code to the nodes and then run the tests. 
# New code must be supported by this script

NUM_ARGS=1
USAGE="Usage: start {xml-test-file} "
USERS="blue"
UPDATE=0

if [ $# -ne $NUM_ARGS ]; then
    echo $USAGE
    exit 1
fi

# lets explore the network and see what is connected
echo "finding nodes..."
source scripts/get_hosts
echo "Found nodes: $nodes"

# lets push the code to the nodes
if [ $UPDATE -gt 0 ]; then
    echo "updating node's code"
    for node in $nodes; do
        ./scripts/sync $node
    done
    echo "done updating code"
fi

echo "Starting nodes..."
ids=""
echo $nodes
for node in $nodes; do
    id=`ssh "$USERS@$node" hostname | cut -c6-`
    ids="$ids$id "
    echo "Starting node-$id"
    ssh "$USERS@$node" "./research/364d-udp/node_start $id" 
done
echo "nodes started: $ids"

echo "Starting experiment."
python python/experiment_AP.py "$ids"
echo "Done."

