#! /bin/bash

dir="tmp"

mkdir $dir

cp ../python/*.py $dir
cp * $dir

python3 "$dir/algo_test.py"
printf "\nAlgorithms test completed\n\n\nStarting encoding test\n\n"
python3 "$dir/encoding_test.py"

rm -rf $dir
