#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: ./sync <node_ip>"
  exit 1
fi

rsync -avz --delete --exclude .git/ --exclude 364d-udp/logs/ --exclude 364d-udp/python/__pycache__/ --exclude *.swp --exclude *.pyc --exclude experiments/ ~/research/ blue@"$1":/home/blue/research

